### PR TITLE
104 transfer opensquirrel tutorial from colab to mkdocs

### PR DESCRIPTION
**Pull request by elenbaasc**

### CODE REVIEW

**Review by rturrado — COMMENTED** [review]
Is there a way I can generate the GitHub pages documentation locally, so that I can view the final results of the changes?

**Comment by elenbaasc** [comment]
You can use:
```bash
mkdocs serve
```

and then visit the url in the output.

**Comment by rturrado** [comment]
> You can use:
> 
> ```shell
> mkdocs serve
> ```
> 
> and then visit the url in the output.

Thanks!

**Review by rturrado — DISMISSED** [review]
Good work, Chris!

I have a patch for one issue I saw with the documentation for `CircuitBuilder`. Do you think you could add it to this PR?

[Fixed_CircuitBuilder_documentation_.patch](https://github.com/QuTech-Delft/OpenSquirrel/files/14694246/Fixed_CircuitBuilder_documentation_.patch)

**Review by rturrado — APPROVED** [review]
Good work!

**Pull request merged**
